on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Run Tests

env:
  APP_KEY: base64:eITSoEAf1AYChhrT7Xq7iDchHKtkM1FgqcuWcsZl91Q=
  CACHE_DRIVER: array
  SESSION_DRIVER: array
  QUEUE_DRIVER: sync
  DB_CONNECTION: testing
  DB_USERNAME: root
  DB_PASSWORD: root
  DB_DATABASE: testing
  DB_HOST: 127.0.0.1
  DB_TESTING_HOST: 127.0.0.1
  DB_PORT: 3306
  APP_ENV: testing

jobs:
  build:
    name: tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        id: composer-cache
        with:
          path: vendor
          key: ${{ runner.os }}-php-v2-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          extensions: curl, mbstring, zip, pcntl, pdo, mysql, pdo_mysql, intl, gd, exif, iconv
          coverage: none

      - name: Install Dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: |
          composer install --prefer-dist --no-interaction --no-progress --no-suggest

      - name: Composer dump-autoload
        if: steps.composer-cache.outputs.cache-hit == 'true'
        run: composer dump-autoload

      - name: Create database
        run: |
          sudo systemctl start mysql.service
          mysql  -u root -proot -e 'CREATE DATABASE IF NOT EXISTS laravel_parallel_testing;'

      - name: Run migrations
        run: php artisan migrate

      - name: Execute tests
        run: php artisan test --parallel --processes 4
